imports:
    - { resource: tables.yml }

services:
    sheer.stopregister.listener:
        class: sheer\stopregister\event\listener
        arguments:
            - @request
            - @template
            - @config
            - @user
            - @log
            - @dbal.conn
            - %core.table_prefix%
        tags:
            - { name: event.listener }
